package uk.co.grahamcox.space.rest

import org.springframework.http.HttpStatus
import java.net.URI

/**
 * Representation of a problem that has occurred on the API.
 * @property type A URI reference that identifies the problem type
 * @property title A short, human-readable summary of the problem type
 * @param statusCode The HTTP status code generated by the origin server for this occurrence of the problem
 * @property instance A URI reference that identifies the specific occurrence of the problem
 * @property detail A human-readable explanation specific to this occurrence of the problem
 */
open class Problem(
        val type: URI,
        val title: String,
        statusCode: HttpStatus,
        val instance: URI? = null,
        val detail: Any? = null
) {
    /** The raw status code */
    val status = statusCode.value()
}
